language: python
python:
  - "3.7-dev"
sudo: required

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
- eval "${MATRIX_EVAL}"
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- g++ --version  
install:
- sudo apt-get install -y gdb  # install gdb
- cmake -DsweetPy_3RD_PARTY_INSTALL_STEP=ON -DsweetPy_WITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release . && make
before_script:
- ulimit -c unlimited -S       # enable core dumps
script:
- cmake -DsweetPy_COMPILE_STEP=ON -DsweetPy_WITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release . && make
- ./Tests/bin/sweetPyTests
after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" ./Tests/bin/sweetPyTests -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
notifications:
  email: false
