language: python
python:
  - "2.7"
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libssl-dev
            - libboost-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script: cmake
before_install:
- eval "${MATRIX_EVAL}"
install:
- cmake -DsweetPy_3RD_PARTY_INSTALL_STEP=ON -DsweetPy_TEST_SUPPORT=ON . && make
script:
- c++ --version && cmake -DsweetPy_COMPILE_STEP=ON -DsweetPy_TEST_SUPPORT=ON . && make VERBOSE=1 && ./Test/bin/sweetPyTests
